# This is a basic workflow to help you get started with Actions

name: ex03

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  doexothree_alpine:
    runs-on: ubuntu-latest
    
    # The type of runner that the job will run on
    container: alpine:10.1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Display Version
      run: cat /etc/os-release | grep 'PRETTY_NAME' | sed -E "s/.*=\"(.+)\"/\1/"
      
  doexothree_archlinux:
    runs-on: ubuntu-latest
    
    # The type of runner that the job will run on
    container: archlinux:10.1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Display Version
      run: cat /etc/os-release | grep 'PRETTY_NAME' | sed -E "s/.*=\"(.+)\"/\1/"
      
  doexothree_fedora:
    runs-on: ubuntu-latest
    
    # The type of runner that the job will run on
    container: fedora:10.1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Display Version
      run: cat /etc/os-release | grep 'PRETTY_NAME' | sed -E "s/.*=\"(.+)\"/\1/"
